src/config/routes.rb
Rails.application.routes.draw do
 
  #devise generated routes
  devise_for :users

  resources :listings

  resources :users 

  resources :conversations do
    resources :messages
  end

  
 #stripe routes 
  get 'payments/success'
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#home", as: "root"
  
  get "/:path", to: "pages#not_found"

end

src/app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!, only: [:index, :new]
    def index
        @conversations = current_user.mailbox.conversations
    end

    def show
        @conversation = current_user.mailbox.conversations.find(params[:id])
    end

    def new
        @recipients = User.all - [current_user]
    end

    def create 
        @recipient = User.find(params[:user_id])
        receipt = current_user.send_message(@recipient, params[:body], params[:subject])
        redirect_to conversation_path(receipt.conversation)
    end


end

src/app/helpers/conversations_helper.rb
module ConversationsHelper
end

src/app/views/conversations/index.html.erb
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>homepagecampingo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/styles.min.css?h=90f8bd7bd325d5a1bbe7cb95eaa88ec1">
    <link rel="stylesheet" href="/assets/stylesheets/application.scss">
    <link rel="stylesheet" href="/assets/stylesheets/conversations.scss">
    <script src="https://use.fontawesome.com/88b5137ddf.js"></script>

</head>

<body class="text-dark">
    <!-- Start: Header Dark -->
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="/">Campingo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#"></a></li>
                            <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Explore&nbsp;</a>
                                <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"  <%= link_to "Listings", listings_path %><a class="dropdown-item" role="presentation" 
                                <%= link_to 'Users', users_path %><a class="dropdown-item" role="presentation"   <%= link_to "Chat", conversations_path %></a></div>
                            </li>
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                            </form><span class="navbar-text"><a class="btn btn-light action-button" role="button" <%= link_to "Logout", destroy_user_session_path %></div>
                        </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">Adventure starts here.</h1>
                        <div class="carousel slide" data-ride="carousel" id="carousel-1">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage1.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage2.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage3.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage4.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage5.jpg" alt="Slide Image"></div>
                            </div>
                            <div>
                                <!-- Start: Previous --><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                                <!-- End: Previous -->
                                <!-- Start: Next --><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                                <!-- End: Next -->
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-1" data-slide-to="1" class="active"></li>
                                <li data-target="#carousel-1" data-slide-to="2"></li>
                                <li data-target="#carousel-1" data-slide-to="3"></li>
                                <li data-target="#carousel-1" data-slide-to="4"></li>
                                <li data-target="#carousel-1" data-slide-to="5"></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Header Dark -->
    <!-- Start: Article Dual Column -->
    <div class="article-dual-column">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
                    <!-- Start: Text -->
                    <div class="text"></div>
                    <!-- End: Text -->
                </div>
            </div>
        </div>
    </div>
    <!-- End: Article Dual Column -->
    <h1></h1>
    <p></p>
    <!-- Start: Team Boxed -->
    <div class="team-boxed">
        <div class="container bg-white">
            <!-- Start: Intro -->
            <div class="intro">
                <h1 class="text-center bg-white">Chats</h1>
            </div>
            <!-- End: Intro -->
        </div>
    </div>
    
    <!-- End: Team Boxed -->
    <div class="text-center">
    <br>
    <br>
    <h2>Inbox</h2>
    
    <!-- Start: 2 Rows 1+1 Columns -->
  
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="clearfix"></div>
                    <% @conversations.each do |conversation|%> <br>
                        <h4> <i class="far fa-envelope"></i>  
                        <%=link_to conversation.subject, conversation_path(conversation)%></h4> 
                    <%end%>  
              </div>
            </div>
        </div>
    </div>
    <!-- End: 2 Rows 1+1 Columns -->
    <div class= "text-center">
    <br>
    <br>
<%= link_to "New Chat", new_conversation_path %>
<%= link_to "Back to Listings", listings_path %>
</div>
    <!-- Start: Footer Basic -->
    <div class="footer-basic">
        <footer>
            <!-- Start: Social Icons -->
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <!-- End: Social Icons -->
            <!-- Start: Links -->
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End: Links -->
            <!-- Start: Copyright -->
            <p class="copyright">Campingo © 2020</p>
            <!-- End: Copyright -->
        </footer>
    </div>
    <!-- End: Footer Basic -->
    <!-- Start: Article Clean -->
    <div class="article-clean"></div>
    <!-- End: Article Clean -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</body>

</html>

src/app/views/conversations/new.html.erb
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>homepagecampingo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/styles.min.css?h=90f8bd7bd325d5a1bbe7cb95eaa88ec1">
    <link rel="stylesheet" href="/assets/stylesheets/application.scss">
    <link rel="stylesheet" href="/assets/stylesheets/conversations.scss">
    <script src="https://use.fontawesome.com/88b5137ddf.js"></script>

</head>

<body class="text-dark">
    <!-- Start: Header Dark -->
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="/">Campingo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#"></a></li>
                            <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Explore&nbsp;</a>
                                <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"  <%= link_to "Listings", listings_path %><a class="dropdown-item" role="presentation" 
                                <%= link_to 'Users', users_path %><a class="dropdown-item" role="presentation"   <%= link_to "Chat", conversations_path %></a></div>
                            </li>
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                            </form><span class="navbar-text"><a class="btn btn-light action-button" role="button" <%= link_to "Logout", destroy_user_session_path %></div>
                        </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">Adventure starts here.</h1>
                        <div class="carousel slide" data-ride="carousel" id="carousel-1">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage1.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage2.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage3.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage4.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage5.jpg" alt="Slide Image"></div>
                            </div>
                            <div>
                                <!-- Start: Previous --><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                                <!-- End: Previous -->
                                <!-- Start: Next --><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                                <!-- End: Next -->
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-1" data-slide-to="1" class="active"></li>
                                <li data-target="#carousel-1" data-slide-to="2"></li>
                                <li data-target="#carousel-1" data-slide-to="3"></li>
                                <li data-target="#carousel-1" data-slide-to="4"></li>
                                <li data-target="#carousel-1" data-slide-to="5"></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Header Dark -->
    <h1></h1>
    <p></p>
    <br>
    <br>
    <!-- Start: Article Dual Column -->
    <div class="article-dual-column">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
                    <!-- Start: Text -->
                    <div class="text"></div>
                    <!-- End: Text -->
                </div>
            </div>
        </div>
    </div>
    <!-- End: Article Dual Column -->
    <h1></h1>
    <p></p>
    <!-- Start: Team Boxed -->
    <div class="team-boxed">
        <div class="container bg-white">
            <!-- Start: Intro -->
            <div class="intro">
                <h2 class="text-center bg-white">Chats</h2>
            </div>
            <!-- End: Intro -->
        </div>
    </div>
    <!-- End: Team Boxed -->
    <!-- Start: 2 Rows 1+1 Columns -->
    
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center">
                        <h3>New Conversation</h3>
                <br>
                <div>
                <%= form_tag conversations_path, method: :post do %>
                <div> 
                <%=select_tag :user_id, options_from_collection_for_select(@recipients, :id, :email) %>
                </div>
                <br>
                <div>
                <%=text_field_tag :subject, nil, placeholder: "Subject" %>
                </div>
                <br>
                <div>
                <%=text_area_tag :body, nil, placeholder: "Leave a comment" %>
                </div>
                <br>
                <%= submit_tag %>
                <% end %>
                <br>

                <%= link_to " My Chats", conversations_path %>
                <br>
            </div>
        </div>
    </div>
</div>
<!-- End: 2 Rows 1+1 Columns -->
    <!-- Start: Footer Basic -->
    <div class="footer-basic">
        <footer>
            <!-- Start: Social Icons -->
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <!-- End: Social Icons -->
            <!-- Start: Links -->
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End: Links -->
            <!-- Start: Copyright -->
            <p class="copyright">Campingo © 2020</p>
            <!-- End: Copyright -->
        </footer>
    </div>
    <!-- End: Footer Basic -->
    <!-- Start: Article Clean -->
    <div class="article-clean"></div>
    <!-- End: Article Clean -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</body>

</html>

src/app/views/conversations/show.html.erb
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>homepagecampingo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/styles.min.css?h=90f8bd7bd325d5a1bbe7cb95eaa88ec1">
    <link rel="stylesheet" href="/assets/stylesheets/application.scss">
    <link rel="stylesheet" href="/assets/stylesheets/conversations.scss">
    <script src="https://use.fontawesome.com/88b5137ddf.js"></script>

</head>

<body class="text-dark">
    <!-- Start: Header Dark -->
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="/">Campingo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#"></a></li>
                            <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Explore&nbsp;</a>
                                <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"  <%= link_to "Listings", listings_path %><a class="dropdown-item" role="presentation" 
                                <%= link_to 'Users', users_path %><a class="dropdown-item" role="presentation"   <%= link_to "Chat", conversations_path %></a></div>
                            </li>
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                        </form><span class="navbar-text"><a class="btn btn-light action-button" role="button" <%= link_to "Logout", destroy_user_session_path %></div>
                        </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">Adventure starts here.</h1>
                        <div class="carousel slide" data-ride="carousel" id="carousel-1">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage1.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage2.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage3.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage4.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage5.jpg" alt="Slide Image"></div>
                            </div>
                            <div>
                                <!-- Start: Previous --><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                                <!-- End: Previous -->
                                <!-- Start: Next --><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                                <!-- End: Next -->
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-1" data-slide-to="1" class="active"></li>
                                <li data-target="#carousel-1" data-slide-to="2"></li>
                                <li data-target="#carousel-1" data-slide-to="3"></li>
                                <li data-target="#carousel-1" data-slide-to="4"></li>
                                <li data-target="#carousel-1" data-slide-to="5"></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Header Dark -->
    <!-- Start: Article Dual Column -->
    <div class="article-dual-column">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
                    <!-- Start: Text -->
                    <div class="text"></div>
                    <!-- End: Text -->
                </div>
            </div>
        </div>
    </div>
    <!-- End: Article Dual Column -->
    <h1></h1>
    <p></p>
    <!-- Start: Team Boxed -->
    <div class="team-boxed">
        <div class="container bg-white">
            <!-- Start: Intro -->
            <div class="intro">
                <h2 class="text-center bg-white">Chat</h2>
            </div>
            <!-- End: Intro -->
        </div>
    </div>
    <!-- End: Team Boxed -->
    <!-- Start: 2 Rows 1+1 Columns -->
    
        <div class="speech-bubble">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center">
                    <p>
            <h4><strong>Subject:</strong>  
            <%= @conversation.subject %></h4><br> 
              
              <% @conversation.receipts_for(current_user).each do |receipt| %>
                  <% message = receipt.message %>  <br>
                  
                 <strong> <%= message.sender.name %>  </strong>
                    says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %> <br>
                  
                  <%= message.body %>
                <% end %>
                </p>
            </div>
                
            <div class="text-center">
            <p>
                 <%= form_tag conversation_messages_path(@conversation), method: :post do %>
                <%=text_area_tag :body %> 
                <br>
                <%=submit_tag %>
                <% end %>
                <br>
                <%= link_to " My Chats", conversations_path %>
            </p>
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- End: 2 Rows 1+1 Columns -->

    <!-- Start: Footer Basic -->
    <div class="footer-basic">
        <footer>
            <!-- Start: Social Icons -->
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <!-- End: Social Icons -->
            <!-- Start: Links -->
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End: Links -->
            <!-- Start: Copyright -->
            <p class="copyright">Campingo © 2020</p>
            <!-- End: Copyright -->
        </footer>
    </div>
    <!-- End: Footer Basic -->
    <!-- Start: Article Clean -->
    <div class="article-clean"></div>
    <!-- End: Article Clean -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</body>

</html>








 