src/config/routes.rb
Rails.application.routes.draw do
 
  #devise generated routes
  devise_for :users

  resources :listings

  resources :users 

  resources :conversations do
    resources :messages
  end

  
 #stripe routes 
  get 'payments/success'
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#home", as: "root"
  
  get "/:path", to: "pages#not_found"

end

src/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_messageable

  has_many :listings
  has_many :orders
  has_one_attached :picture
  
  def name
    "#{username}"
  end

  def mailboxer_email(object)
    nil
  end

end

src/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_listings = @user.listings
   
  end

  def index
    @users = User.all 
  
  end

end

src/app/helpers/users_helper.rb
module UsersHelper
    def full_name
        @user.first_name + " " + @user.last_name
    end
end

src/app/views/users/index.html.erb
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>homepagecampingo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/styles.min.css?h=90f8bd7bd325d5a1bbe7cb95eaa88ec1">
    <link rel="stylesheet" href="/assets/stylesheets/application.scss">
    <link rel="stylesheet" href="/assets/stylesheets/users.scss">
    <script src="https://use.fontawesome.com/88b5137ddf.js"></script>

</head>

<body class="text-dark">
    <!-- Start: Header Dark -->
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="/">Campingo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#"></a></li>
                            <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Explore&nbsp;</a>
                                <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"  <%= link_to "Listings", listings_path %><a class="dropdown-item" role="presentation" 
                                <%= link_to 'Users', users_path %><a class="dropdown-item" role="presentation"   <%= link_to "Chat", conversations_path %></a></div>
                            </li>
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                            </form><span class="navbar-text"><a class="btn btn-light action-button" role="button" <%= link_to "Logout", destroy_user_session_path %></div>
                        </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">Adventure starts here.</h1>
                        <div class="carousel slide" data-ride="carousel" id="carousel-1">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage1.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage2.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage3.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage4.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage5.jpg" alt="Slide Image"></div>
                            </div>
                            <div>
                                <!-- Start: Previous --><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                                <!-- End: Previous -->
                                <!-- Start: Next --><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                                <!-- End: Next -->
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-1" data-slide-to="1" class="active"></li>
                                <li data-target="#carousel-1" data-slide-to="2"></li>
                                <li data-target="#carousel-1" data-slide-to="3"></li>
                                <li data-target="#carousel-1" data-slide-to="4"></li>
                                <li data-target="#carousel-1" data-slide-to="5"></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Header Dark -->
    <!-- Start: Article Dual Column -->
    <div class="article-dual-column">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
                    <!-- Start: Text -->
                    <div class="text"></div>
                    <!-- End: Text -->
                </div>
            </div>
        </div>
    </div>
    <!-- End: Article Dual Column -->
    <h1></h1>
    <p></p>
    <!-- Start: Team Boxed -->
    <div class="team-boxed">
        <div class="container">
            <!-- Start: Intro -->
            <div class="intro">
                <h2 class="text-center">Campingo Users</h2><br>
                <p class="text-center">Meet our users</p><br>
            </div>
            <!-- End: Intro -->
            <!-- Start: People -->
            
           
    <div class="row people">
            <% @users.each do |user| %>
                <div class="col-md-6 col-lg-4 item">
                <% if user.picture.attached? %>
                <%= image_tag user.picture, width: "200px" %>
                <% else %>
                <%= image_tag 'default.jpg', width: "200px" %>
                <% end %>
                <br>
                <br>
                    <h5 class="name"><strong>Username:</strong><%=link_to user.username, user_path(user)%></h5>
                    <p class="bio"><strong>Bio:</strong> <%=link_to user.bio, user_path(user)%></p>
                    <div class="social"><a href="#"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
            </div>
        <% end %>
    </div>

<div class="text-center">
 <%= link_to 'Back to Listings', listings_path %>
 </div>
            <!-- End: People -->
        </div>
    </div>
    <!-- End: Team Boxed -->
    <!-- Start: Footer Basic -->
    <div class="footer-basic">
        <footer>
            <!-- Start: Social Icons -->
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <!-- End: Social Icons -->
            <!-- Start: Links -->
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End: Links -->
            <!-- Start: Copyright -->
            <p class="copyright">Campingo © 2020</p>
            <!-- End: Copyright -->
        </footer>
    </div>
    <!-- End: Footer Basic -->
    <!-- Start: Article Clean -->
    <div class="article-clean"></div>
    <!-- End: Article Clean -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</body>

</html>

src/app/views/users/show.html.erb
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>homepagecampingo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/styles.min.css?h=90f8bd7bd325d5a1bbe7cb95eaa88ec1">
    <link rel="stylesheet" href="/assets/stylesheets/application.scss">
    <link rel="stylesheet" href="/assets/stylesheets/users.scss">
    <script src="https://use.fontawesome.com/88b5137ddf.js"></script>

</head>

<body class="text-dark">
    <!-- Start: Header Dark -->
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="/">Campingo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#"></a></li>
                            <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Explore&nbsp;</a>
                                <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"  <%= link_to "Listings", listings_path %><a class="dropdown-item" role="presentation" 
                                <%= link_to 'Users', users_path %><a class="dropdown-item" role="presentation"   <%= link_to "Chat", conversations_path %></a></div>
                            </li>
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                            </form><span class="navbar-text"><a class="btn btn-light action-button" role="button" <%= link_to "Logout", destroy_user_session_path %></div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">Adventure starts here.</h1>
                        <div class="carousel slide" data-ride="carousel" id="carousel-1">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage1.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage2.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage3.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage4.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage5.jpg" alt="Slide Image"></div>
                            </div>
                            <div>
                                <!-- Start: Previous --><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                                <!-- End: Previous -->
                                <!-- Start: Next --><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                                <!-- End: Next -->
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-1" data-slide-to="1" class="active"></li>
                                <li data-target="#carousel-1" data-slide-to="2"></li>
                                <li data-target="#carousel-1" data-slide-to="3"></li>
                                <li data-target="#carousel-1" data-slide-to="4"></li>
                                <li data-target="#carousel-1" data-slide-to="5"></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Header Dark -->
    <!-- Start: Article Dual Column -->
    <div class="article-dual-column">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-lg-7 offset-md-1 offset-lg-0">
                    <!-- Start: Text -->
                    <div class="text"></div>
                    <!-- End: Text -->
                </div>
            </div>
        </div>
    </div>
    <!-- End: Article Dual Column -->
    <h1></h1>
    <p></p>
    <!-- Start: Team Boxed -->
    <div class="team-boxed">
        <div class="container">
            <!-- Start: Intro -->
            <div class="intro">
                <h2 class="text-center">Profile</h2>
            </div>
            <!-- End: Intro -->
            <!-- Start: People -->
            <div class="row justify-content-center people">
                <div class="col-md-6 col-lg-4 item">
                    <div class="box"><img class="rounded-circle" src="/assets/img/3.jpg?h=f30bab0e45dae0c5b3606e27d0a776cd">
                    <br>
                    <br>
                        <h3 class="name"><%= full_name %></strong></h3>
                        
                            <p>
                            <strong>Username:</strong>
                            <%= @user.username %></p>
                            </p>

                            <p>
                            <strong>Email:</strong>
                            <%= @user.email %></p>
                            </p>

                            <p>
                            <strong>Location:</strong>
                            <%= @user.location %></p>
                            </p>

                            <p>
                            <strong>Phone:</strong>
                            <%= @user.phone %></p>
                            </p>

                            <p>
                            <strong>Phone:</strong>
                            <%= @user.bio %></p>
                            </p>

                            <p>
                            <strong>Picture:</strong>
                            <%= @user.picture %></p>
                            </p>

                            <p>
                            <strong>Listings:</strong>
                            <% @user_listings.each do |listing| %>
                            <%=link_to listing.title, listing_path(listing) %>
                            <%end%>
                            </p>               
                 </p>
         <div class="social"><a href="#"><i class="fa fa-facebook-official"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-instagram"></i></a></div>
  </div>
 </div>
 <!-- End: People -->
        </div>
    </div>
    <!-- End: Team Boxed -->
    <br>
    <br>
    <div class="text-center">
    <div class="buttons">
        <% if current_user.id == @user.id  %>

        <%= link_to "New Listing", new_listing_path %><br>
       
        <%=link_to "Edit Profile", edit_user_registration_path(@user)%><br>
        
        <%= link_to "Conversations", conversations_path%><br>
      
        <%=link_to "Listings", listings_path%> <br>
       
        <%=link_to "Users ", users_path%><br>

        <% else %>

        <%=link_to "Edit Profile", edit_user_registration_path(@user) %><br>
      
        <%=link_to "Users ", users_path%><br>
        
        <%=link_to "Listings", listings_path%><br>
       
        <% end %>
        </div>
        </div>
    <!-- Start: Footer Basic -->
    <div class="footer-basic">
        <footer>
            <!-- Start: Social Icons -->
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <!-- End: Social Icons -->
            <!-- Start: Links -->
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End: Links -->
            <!-- Start: Copyright -->
            <p class="copyright">Campingo © 2020</p>
            <!-- End: Copyright -->
        </footer>
    </div>
    <!-- End: Footer Basic -->
    <!-- Start: Article Clean -->
    <div class="article-clean"></div>
    <!-- End: Article Clean -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
</body>

</html>