src/config/routes.rb
Rails.application.routes.draw do
 
  #devise generated routes
  devise_for :users

  resources :listings

  resources :users 

  resources :conversations do
    resources :messages
  end

  
 #stripe routes 
  get 'payments/success'
  get "/payments/success", to: "payments#success"
  post "/payments/webhook", to: "payments#webhook"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/", to: "pages#home", as: "root"
  
  get "/:path", to: "pages#not_found"

end

src/app/models/listing.rb
class Listing < ApplicationRecord

  #validates :title, :description, :suburb, :city, :price, :deposit, :available_from, :available_to,  presence: true
  belongs_to :category
  has_one_attached :picture
  belongs_to :user
  has_one :order
end

src/app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show]
  before_action :set_user_listing, only: [:edit, :update, :destroy]
  before_action :set_category, only: [:new, :edit]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
      @q = Listing.ransack(params[:q])
      @listings = @q.result.includes(category: [])
      @totallistings = Listing.all
      @totallistings.sort_by(&:created_at)
      
     
  end

  # GET /listings/1
  # GET /listings/1.json
  def show

    if current_user #user_signed_in?
    session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
            name: @listing.title,
            description: @listing.description,
            amount: @listing.deposit * 100,
            currency: 'aud',
            quantity: 1,
        }],
        payment_intent_data: {
            metadata: {
                user_id: current_user.id,
                listing_id: @listing.id
            }
        },
        success_url: "#{root_url}payments/success?userId=#{current_user.id}&listingId=#{@listing.id}",
        cancel_url: "#{root_url}listings"
    )

    @session_id = session.id
    end 
end


  # GET /listings/new
  def new
    @listing = current_user.listings.build 
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = current_user.listings.build(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully deleted.' }
      format.json { head :no_content }
    end
  end

 


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
      #@listing = current_user.listings.find(params[:id])#
    end
    
    # method to set user listing
    def set_user_listing
      id = params[:id]
      @listing = current_user.listings.find_by_id(id)
      if
       @listing == nil
        redirect_to listings_path
      end
  end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :description, :category_id, :suburb, :city, :price, :deposit, :availability, :picture, :user_id, :bought, :to, :from)
    end

  def set_category
    @categories = Category.all 
  end


end

src/app/helpers/listings_helper.rb
module ListingsHelper
end

src/app/views/listings/edit.html.erb
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>homepagecampingo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/styles.min.css?h=90f8bd7bd325d5a1bbe7cb95eaa88ec1">
    <link rel="stylesheet" href="/assets/stylesheets/application.scss">
    <link rel="stylesheet" href="/assets/stylesheets/listings.scss">
    <script src="https://use.fontawesome.com/88b5137ddf.js"></script>

</head>

<body class="text-dark">
    <!-- Start: Header Dark -->
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="/">Campingo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#"></a></li>
                            <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Explore&nbsp;</a>
                                <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"  <%= link_to "Listings", listings_path %><a class="dropdown-item" role="presentation" 
                                <%= link_to 'Users', users_path %><a class="dropdown-item" role="presentation"   <%= link_to "Chat", conversations_path %></div>
                            </li>
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                            </form><span class="navbar-text"><a class="btn btn-light action-button" role="button" <%= link_to "Logout", destroy_user_session_path %></div>
                        </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">Adventure starts here.</h1>
                        <div class="carousel slide" data-ride="carousel" id="carousel-1">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage1.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage2.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage3.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage4.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage5.jpg" alt="Slide Image"></div>
                            </div>
                            <div>
                                <!-- Start: Previous --><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                                <!-- End: Previous -->
                                <!-- Start: Next --><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                                <!-- End: Next -->
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-1" data-slide-to="1" class="active"></li>
                                <li data-target="#carousel-1" data-slide-to="2"></li>
                                <li data-target="#carousel-1" data-slide-to="3"></li>
                                <li data-target="#carousel-1" data-slide-to="4"></li>
                                <li data-target="#carousel-1" data-slide-to="5"></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Header Dark -->
    <br>
    <br>
    <!-- Start: Text -->
   
                        <div class="text-center">
                        <h1>Edit Listing</h1>
                   
                        <%= render "form", listing: @listing, category: @categories %>
                     
                       
                        <br>
                        <div class="buttons">
                        <%= link_to 'Show', @listing , class: "btn btn-primary" %>
                        <%= link_to 'Back', listings_path, class: "btn btn-primary" %>
                        
                        </div>
<!-- End: Text -->
    <!-- Start: Footer Basic -->
    <div class="footer-basic">
        <footer>
            <!-- Start: Social Icons -->
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <!-- End: Social Icons -->
            <!-- Start: Links -->
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End: Links -->
            <!-- Start: Copyright -->
            <p class="copyright">Campingo © 2020</p>
            <!-- End: Copyright -->
        </footer>
    </div>
    <!-- End: Footer Basic -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    </body>
    
    </html>

src/app/views/listings/index.html.erb
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>homepagecampingo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/styles.min.css?h=90f8bd7bd325d5a1bbe7cb95eaa88ec1">
    <link rel="stylesheet" href="/assets/stylesheets/application.scss">
    <link rel="stylesheet" href="/assets/stylesheets/listings.scss">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/88b5137ddf.js"></script>

</head>

<body class="text-dark">
    <!-- Start: Header Dark -->
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="/">Campingo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#"></a></li>
                            <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Explore&nbsp;</a>
                                <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"  <%= link_to "Listings", listings_path %><a class="dropdown-item" role="presentation" 
                                <%= link_to 'Users', users_path %><a class="dropdown-item" role="presentation"   <%= link_to "Chat", conversations_path %></a></div>
                            </li>
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                            </form><span class="navbar-text"><a class="btn btn-light action-button" role="button" <%= link_to "Logout", destroy_user_session_path %></div>
                        </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">Adventure starts here.</h1>
                        <div class="carousel slide" data-ride="carousel" id="carousel-1">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage1.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage2.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage3.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage4.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage5.jpg" alt="Slide Image"></div>
                            </div>
                            <div>
                                <!-- Start: Previous --><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                                <!-- End: Previous -->
                                <!-- Start: Next --><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                                <!-- End: Next -->
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-1" data-slide-to="1" class="active"></li>
                                <li data-target="#carousel-1" data-slide-to="2"></li>
                                <li data-target="#carousel-1" data-slide-to="3"></li>
                                <li data-target="#carousel-1" data-slide-to="4"></li>
                                <li data-target="#carousel-1" data-slide-to="5"></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Header Dark -->
    <!-- Start: Lightbox Gallery -->
    <div class="photo-gallery"></div>
    <!-- End: Lightbox Gallery -->
    <!-- Start: Projects Clean -->
    <div class="projects-clean">
        <div class="container">
            <!-- Start: Intro -->
            <div class="intro">
                <h2 class="text-center">Camping Gear</h2>
                <p class="text-center">Take a look at our collection</p>
            </div>
            <br>
            <br>
            
            <div class="text-center">
            <%= search_form_for @q do |f| %>
            <%= f.search_field :title_or_description_or_suburb_cont %>
            <% Category.all.each do |category|%>
            <%= check_box_tag "q[category_name_cont_any][]", category.name%>
            <%= category.name %><% end %>
            <%= f.submit %>
                <% end %>
            </div>
            <!-- End: Intro -->
            <!-- Start: Projects -->
    
            <div class="row projects">
            <% @listings.each do |listing| %>
                <% if !listing.bought? then %>
                <div class="col-sm-6 col-lg-4 item">
                <% if listing.picture.attached? %>
                <%= image_tag listing.picture, width: "200px" %>
                <% else %>
                <%= image_tag 'default.jpg', width: "200px" %>
                <% end %>
                
                    <h3 class="name"><%= listing.title%></h3>
                    <p class="description">description: <%= listing.description%></p><br>
                    <p class="category">category: <%= listing.category.name %></p>
                    <p class="price">price: <%= listing.price%></p>
                    <p class="location">location: <%= listing.suburb%></p>
                 <%= link_to 'Show', listing %>|
                 <%= link_to 'Edit', edit_listing_path(listing) if user_signed_in? and listing.user.id == current_user.id  %>|
                  <%= link_to 'Delete', listing, method: :delete, data: { confirm: 'Are you sure?' } if user_signed_in? and listing.user.id == current_user.id  %>
                </div>
                <%end%>
                <%end%>
            </div>
            
            <!-- End: Projects -->
        </div>
    </div>
    <!-- End: Projects Clean -->
    <p></p>
    <!-- Start: Projects Clean -->
    <div class="projects-clean">
        <div class="container">
            <!-- Start: Intro -->
            <div class="intro"></div>
            <!-- End: Intro -->
        </div>
    </div>
    <!-- End: Projects Clean -->
    <div class="text-center">
    <div class="buttons">
    <%= link_to "New Listing", new_listing_path, class: "btn btn-primary" %>
    </div>
    <br>
    <br>
      <nav>
            <ul class="pagination justify-content-center">
                <li class="page-item"><a class="page-link" href="#" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">4</a></li>
                <li class="page-item"><a class="page-link" href="#">5</a></li>
                <li class="page-item"><a class="page-link" href="#" aria-label="Next"><span aria-hidden="true">»</span></a></li>
            </ul>
        </nav>
        </div>
        </div>
        <footer>
        <!-- Start: Footer Basic -->
        <div class="footer-basic">
            <!-- Start: Social Icons -->
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <!-- End: Social Icons -->
            <!-- Start: Links -->
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End: Links -->
            <!-- Start: Copyright -->
            <p class="copyright">Campingo © 2020</p>
            <!-- End: Copyright -->
        </footer>
    </div>
    <!-- End: Footer Basic -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
    </body>
    
    </html>

src/app/views/listings/show.html.erb
<!DOCTYPE html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>homepagecampingo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/assets/css/styles.min.css?h=90f8bd7bd325d5a1bbe7cb95eaa88ec1">
    <link rel="stylesheet" href="/assets/stylesheets/application.scss">
    <link rel="stylesheet" href="/assets/stylesheets/listings.scss">
    <script src="https://use.fontawesome.com/88b5137ddf.js"></script>
    <link href="styles/glDatePicker.default.css" rel="stylesheet" type="text/css">
    <script type=text/javascript src="your_jquery_ui.js"></script>
    

</head>

<body class="text-dark">
    <!-- Start: Header Dark -->
    <div>
        <div class="header-dark">
            <nav class="navbar navbar-dark navbar-expand-lg navigation-clean-search">
                <div class="container"><a class="navbar-brand" href="/">Campingo</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse"
                        id="navcol-1">
                        <ul class="nav navbar-nav">
                            <li class="nav-item" role="presentation"><a class="nav-link" href="#"></a></li>
                            <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Explore&nbsp;</a>
                                <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation"  <%= link_to "Listings", listings_path %><a class="dropdown-item" role="presentation" 
                                <%= link_to 'Users', users_path %><a class="dropdown-item" role="presentation"   <%= link_to "Chat", conversations_path %></a></div>
                            </li>
                        </ul>
                        <form class="form-inline mr-auto" target="_self">
                            <div class="form-group"><label for="search-field"></label><input class="form-control search-field" type="search" id="search-field" name="search"></div>
                            </form><span class="navbar-text"><a class="btn btn-light action-button" role="button" <%= link_to "Logout", destroy_user_session_path %>
                        </div>
            </nav>
            <div class="container hero">
                <div class="row">
                    <div class="col-md-8 offset-md-2">
                        <h1 class="text-center">Adventure starts here.</h1>
                        <div class="carousel slide" data-ride="carousel" id="carousel-1">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage1.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage2.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage3.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage4.jpg" alt="Slide Image"></div>
                                <div class="carousel-item"><img class="w-100 d-block" src="http://localhost:3000/assets/homepage/homepage5.jpg" alt="Slide Image"></div>
                            </div>
                            <div>
                                <!-- Start: Previous --><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a>
                                <!-- End: Previous -->
                                <!-- Start: Next --><a class="carousel-control-next" href="#carousel-1" role="button" data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a>
                                <!-- End: Next -->
                            </div>
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-1" data-slide-to="1" class="active"></li>
                                <li data-target="#carousel-1" data-slide-to="2"></li>
                                <li data-target="#carousel-1" data-slide-to="3"></li>
                                <li data-target="#carousel-1" data-slide-to="4"></li>
                                <li data-target="#carousel-1" data-slide-to="5"></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End: Header Dark -->
    <br>
    <br>
    <!-- Start: Text -->
      <div class="text-center">
                                                     
    <p>
      <strong>Title:</strong>
      <%= @listing.title %>
    </p>

<%if @listing.picture.attached?%>
    <%= image_tag @listing.picture, width: "500px"%>
  <%else%>
  <%=image_tag 'default.jpg', width: "500px"%>
    <%end%>
    
    <p>
      <strong>Description:</strong>
      <%= @listing.description %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @listing.category.name %>
    </p>

    <p>
      <strong>Suburb:</strong>
      <%= @listing.suburb %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @listing.city %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @listing.price %>
    </p>

    <p>
      <strong>Deposit:</strong>
      <%= @listing.deposit %>
    </p>

    <p>
    
    <strong>Lease Start:</strong>
    <%= @listing.from.strftime("%d/%m/%Y") %>
    </p>


    <p>
    <strong>Lease End:</strong>
    <%=  @listing.to.strftime("%d/%m/%Y") %>
    </p>


    <p>
      <strong>User:</strong>
      <%= @listing.user.username %> 
    </p>


    <button data-stripe="payment">
      Pay Deposit <%= number_to_currency(@listing.deposit) %>
    </button>

        
      <script src="https://js.stripe.com/v3/"></script>
        
        <script>
          document
            .querySelector("[data-stripe='payment']")
            .addEventListener("click", () => {
              const stripe = Stripe(
                "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
              );
        
              stripe.redirectToCheckout({
                sessionId: "<%= @session_id %>"
              });
            });
        </script>
        <br>
        <br>

        <div class="buttons">
        <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-primary" if user_signed_in? and @listing.user.id == current_user.id %>
        <%= link_to 'Back', listings_path, class: "btn btn-primary" %> 
        </div>
</p>
    </div>
      <!-- End: Text -->
     </div>
   </div>
</div>
    </div>
    <!-- Start: Footer Basic -->
    <div class="footer-basic">
        <footer>
            <!-- Start: Social Icons -->
            <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a></div>
            <!-- End: Social Icons -->
            <!-- Start: Links -->
            <ul class="list-inline">
                <li class="list-inline-item"><a href="#">Home</a></li>
                <li class="list-inline-item"><a href="#">Services</a></li>
                <li class="list-inline-item"><a href="#">About</a></li>
                <li class="list-inline-item"><a href="#">Terms</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <!-- End: Links -->
            <!-- Start: Copyright -->
            <p class="copyright">Campingo © 2020</p>
            <!-- End: Copyright -->
        </footer>
    </div>
    <!-- End: Footer Basic -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    </body>
    
    </html>